---
title: "basic VBD model"
output: html_document
date: "2026-05-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic VBD model

Basic VBD model using odin based on equations from Marini et al (2018)

```{r model}
library(odin2)
library(dust2)
library(monty)
library(ggplot2)

sir <- odin({
  
  deriv(Sm) <- (mu_m*Nm) - (b*p_bm*(Ib/Nb)+mu_m)*Sm #assuming birth and death rate are the same for simplicity
  
  deriv(Em) <- (b*p_bm*(Ib/Nb)*Sm)-((theta_m+mu_m)*Em)
  
  deriv(Im) <- (theta_m*Em)-(mu_m*Im)
  
  deriv(Sb) <- gamma*Nb - (mu_b+b*p_mb*(Im/Nb))*Sb
  
  deriv(Eb) <- b*p_mb*(Im/Nb)*Sb - (mu_b+theta_b)*Eb
  
  deriv(Ib) <- theta_b*Eb-(mu_b+sigma)*Ib 
  
  deriv(Rb) <- (sigma*Ib) - (mu_b*Rb)
  
  
  initial(Sm) <- Nm - Im0
  
  initial(Em) <- 0
  
  initial(Im) <- Im0
  
  initial(Sb) <- Nb
  
  initial(Eb) <- 0
  
  initial(Ib) <- 0
  
  initial(Rb) <- 0
  
  #fixed parameters
  
  Nm <- parameter(1000) 
  
  Nb <- parameter(1000) 
  
  Im0 <- parameter(5)
  
  mu_m <- parameter(0.02) 
  
  b <- parameter(0.3) 
  
  p_bm <- parameter(0.9) 
  
  theta_m <- parameter(0.1) 
  
  gamma <- parameter(0.0015) 
  
  mu_b <- parameter(0.0015) 
  
  p_mb <- parameter(0.9) 
  
  theta_b <- parameter(0.15) 
  
  sigma <- parameter(0.1) 
})

#creating dust system

pars <- list()

sys <- dust_system_create(sir, pars)

dust_system_state(sys)

#use initial condition from model
dust_system_set_state_initial(sys)
dust_system_state(sys)

s <- dust_system_state(sys)
dust_unpack_state(sys, s)

t <- seq(0, 300, by = 0.25) #150
y <- dust_system_simulate(sys, t)
```

## Plots

Bird infections:

```{r Ib plot, echo=TRUE}
state <- dust_unpack_state(sys, y)
df <- data.frame(t = t, Ib = state$Ib)
ggplot(df, aes(x = t)) +
  geom_line(aes(y = Ib), linewidth = 0.6) +
  labs(
    x = "Time (days)",
    y = "Infected birds",
    title = "Infections over time"
  ) +
  theme_minimal()+
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    axis.ticks = element_line(colour = "black"),
  )
```

Mosquito infections:

```{r Im plot, echo=TRUE}
state <- dust_unpack_state(sys, y)
df <- data.frame(t = t, Im = state$Im)
ggplot(df, aes(x = t)) +
  geom_line(aes(y = Im), linewidth = 0.6) +
  labs(
    x = "Time (days)",
    y = "Infected mosquitoes",
    title = "Mosquito infections over time"
  ) +
  theme_minimal()+
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    axis.ticks = element_line(colour = "black"),
  )
```

Total bird population:

```{r Nb plot, echo=TRUE}
state <- dust_unpack_state(sys, y)
Nb <- state$Sb + state$Eb + state$Ib + state$Rb
df <- data.frame(t = t, Nb = Nb)
ggplot(df, aes(x = t)) +
  geom_line(aes(y = Nb), linewidth = 0.6) +
  labs(
    x = "Time (days)",
    y = "Total birds",
    title = "Bird population over time"
  ) +
  theme_minimal()+
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    axis.ticks = element_line(colour = "black"),
  )
```

Total mosquito population:

```{r Nm plot, echo=TRUE}
state <- dust_unpack_state(sys, y)
Nm <- state$Sm + state$Em + state$Im
df <- data.frame(t = t, Nm = Nm)
ggplot(df, aes(x = t)) +
  geom_line(aes(y = Nm), linewidth = 0.6) +
  labs(
    x = "Time (days)",
    y = "Total mosquitoes",
    title = "Mosquito population over time"
  ) +
  theme_minimal()+
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    axis.ticks = element_line(colour = "black"),
  )
```

Recovered birds:

```{r Rb plot, echo=TRUE}
state <- dust_unpack_state(sys, y)
df <- data.frame(t = t, Rb = state$Rb)
ggplot(df, aes(x = t)) +
  geom_line(aes(y = Rb), linewidth = 0.6) +
  labs(
    x = "Time (days)",
    y = "Recovered birds",
    title = "Recovered birds over time"
  ) +
  theme_minimal()+
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    axis.ticks = element_line(colour = "black"),
  )
```

Susceptible birds:

```{r Sb plot, echo=TRUE}
state <- dust_unpack_state(sys, y)
df <- data.frame(t = t, Sb = state$Sb)
ggplot(df, aes(x = t)) +
  geom_line(aes(y = Sb), linewidth = 0.6) +
  labs(
    x = "Time (days)",
    y = "Susceptible birds",
    title = "Susceptible birds over time"
  ) +
  theme_minimal()+
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    axis.ticks = element_line(colour = "black"),
  )
```

Susceptible mosquitoes:

```{r Sm plot, echo=TRUE}
state <- dust_unpack_state(sys, y)
df <- data.frame(t = t, Sm = state$Sm)
ggplot(df, aes(x = t)) +
  geom_line(aes(y = Sm), linewidth = 0.6) +
  labs(
    x = "Time (days)",
    y = "Susceptible mosquitoes",
    title = "Susceptible mosquitoes over time"
  ) +
  theme_minimal()+
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    axis.ticks = element_line(colour = "black"),
  )
```

Reset to run again:

```{r reset, echo=TRUE}
dust_system_time(sys) # current time
dust_system_set_time(sys, 0) # reset time
```

